exec-once= qs -c noctalia-shell

animations=1
shadows=0
border_radius=6
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0
animation_fade_in=0
animation_fade_out=1
animation_type_open=slide
animation_type_close=slide
animation_duration_move=500
animation_duration_open=300
animation_duration_tag=300
animation_duration_close=300
animation_duration_focus=0

#fix for lag or stuttering games
#syncobj_enable=1

#tearing
#allow_tearing=1

#Qt
env=QT_QPA_PLATFORM,wayland
env=QT_QPA_PLATFORMTHEME,qt6ct
env=QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=QT_STYLE_OVERRIDE,kvantum

#env
env=XDG_SESSION_TYPE,wayland
env=GDK_BACKEND,wayland,x11,*
env=SDL_VIDEODRIVER,wayland
env=CLUTTER_BACKEND,wayland

#mozilla
env=MOZ_ENABLE_WAYLAND,1

# Scroller Layout Setting
scroller_structs=20
scroller_default_proportion=0.50
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
scroller_default_proportion_single=1.0
scroller_ignore_proportion_single=1
scroller_proportion_preset=0.5,1.0

# Overview Setting
hotarea_size=2
enable_hotarea=1
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

# Misc
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
drag_tile_to_tile=1

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0
mouse_accel_profile=0
cursor_size=36
cursor_theme=LyraB-cursors

# Appearance
gappih=10
gappiv=10
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=2
rootcolor=0x1e1e2eff
bordercolor=0x1e1e2eff
focuscolor=0x83a4e7ff
maximizescreencolor=0x83a4e7ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
